# Generated by Django 3.2.25 on 2024-05-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
