# Generated by Django 3.2.25 on 2024-05-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_door_is_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
